Add media icons
vtex-apps/store-icons pull request #53
Opened 2020-09-21 13:27 UTC by vitorflg

#### What problem is this solving?

Add media icons for video block

#### How to test it?

The icons are being used in the video block in the following workspace:

https://vitorflg--storecomponents.myvtex.com/

2020-09-21 15:32 UTC, Klynger requested changes

2020-09-21 15:32 UTC, Klynger commented on store/interfaces.json
> +    "component": ",IconPlay"
```suggestion
    "component": "IconPlay"
```

2020-09-29 20:24 UTC, klzns requested changes

2020-09-29 20:24 UTC, klzns commented on docs/README.md
> +| 'VolumeOffIcon'      |
Can we change to use camelCase?

2020-09-29 20:24 UTC, klzns commented on styles/iconpacks/iconpack.svg
> +      <rect width="6" height="16" fill="white"/>
Change colors to `currentColor`
```suggestion
      <rect width="6" height="16" fill="currentColor"/>
```

2020-09-29 20:44 UTC, klzns requested changes
Also, rebase and push force branch

2020-09-29 20:44 UTC, klzns commented on styles/iconpacks/iconpack.svg
> +      <path d="M1 6.49999L1 13C1 14.1046 1.89543 15 3 15H9.49997C10.6045 15 11.5 14.1046 11.5 13V6.49999C11.5 5.39542 10.6045 4.49999 9.49997 4.49999H3C1.89543 4.49999 1 5.39542 1 6.49999Z" fill="cur
I would keep this one as it was
```suggestion
      <path d="M1 6.49999L1 13C1 14.1046 1.89543 15 3 15H9.49997C10.6045 15 11.5 14.1046 11.5 13V6.49999C11.5 5.39542 10.6045 4.49999 9.49997 4.49999H3C1.89543 4.49999 1 5.39542 1 6.49999Z" fill="currentColor" stroke="white" stroke-width="2" stroke-miterlimit="10" stroke-linecap="square"/>
```

2020-09-29 20:50 UTC, kaisermann approved these changes

2020-10-01 16:58 UTC, klzns requested changes

2020-10-01 16:58 UTC, klzns commented on react/IconVolumeOff.tsx
> +  return <Icon id="sti-volume-off" handle="VolumeOffIcon" {...props} />
```suggestion
  return <Icon id="sti-volume-off" handle="volumeOffIcon" {...props} />
```

2020-10-01 17:27 UTC, klzns approved these changes

2020-10-01 21:09 UTC, icazevedo approved these changes

2020-10-05 18:50 UTC, merged